/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ContentPanel.java
 *
 * Created on Dec 5, 2017, 4:34:38 PM
 */

package org.sunspotworld.demo;

/**
 *
 * @author userrsus
 */
public class ContentPanel extends javax.swing.JPanel {

    /** Creates new form ContentPanel */
    private String content;
    public ContentPanel() {
        initComponents();
        content="";
    }
    public void addText(String message)
    {
        content+=message+" \n";
        TextPane1.setText(content);
        TextPane1.setCaretPosition(TextPane1.getDocument().getLength());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextPane1 = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(TextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TextPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
